<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1541f12173b2d1d7907b2a968ede61bd
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Lcobucci\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Lcobucci\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/lcobucci/jwt/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1541f12173b2d1d7907b2a968ede61bd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1541f12173b2d1d7907b2a968ede61bd::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
